<?xml version="1.0"?>
<robot name="forklift" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- 定义常量参数 -->
  <xacro:property name="clearance" value="0.008"/> <!-- 增加安全间隙 -->
  <xacro:property name="wheel_radius" value="0.2" />
  <xacro:property name="wheelbase" value="1.7" />
  <xacro:property name="chassis_length" value="2.3" />
  <xacro:property name="chassis_width" value="1.5" />
  <xacro:property name="chassis_height" value="0.5" />
  <xacro:property name="track_width" value="1.6" />
  
  <!-- 质量参数 -->
  <xacro:property name="chassis_mass" value="100" />
  <xacro:property name="front_wheel_mass" value="30" /> 
  <xacro:property name="back_wheel_mass" value="5" /> 

  <!-- 坐标位置计算 -->
  <xacro:property name="wheel_z" value="-${chassis_height/2 + wheel_radius + clearance}" />
  <xacro:property name="front_wheel_x" value="${wheelbase/2}" />
  <xacro:property name="rear_wheel_x" value="${-wheelbase/2}" />
  <xacro:property name="rear_wheel_y" value="${track_width/2}" />
  <xacro:property name="lidar_z" value="${chassis_height / 2 + 0.05}" />
  <!-- 定义一些常用的材料和颜色 -->

  <!-- 指定前轮和后轮为黑色 -->
  <material name="red">
    <color rgba="0.8 0.1 0.1 1"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1"/>
  </material>
  <material name="blue">
    <color rgba="0.1 0.1 0.8 1"/>
  </material>

  <!-- 地面投影基准坐标系 -->
  <link name="base_footprint" />

  <!-- 底盘 -->
  <link name="base_link">

    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <collision>
      <origin xyz="-0.1 0 0.0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="-0.15 0 0.0" rpy="0 0 0"/>
      <inertia ixx="${chassis_mass*(chassis_width**2 + chassis_height**2)/12}" 
               ixy="0" ixz="0"
               iyy="${chassis_mass*(chassis_length**2 + chassis_height**2)/12}" 
               iyz="0"
               izz="${chassis_mass*(chassis_length**2 + chassis_width**2)/12}"/>
    </inertial>
  </link>

  <link name="imu_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
    </collision>
    
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0"
               iyy="0.0001" iyz="0"
               izz="0.0001"/>
    </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height/2 - 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- base_footprint 到 base_link 的连接 -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius * 2 + chassis_height/2 + clearance}" rpy="0 0 0"/>
  </joint>

  <!-- 激光雷达 -->
  <link name="scanner_link">
    <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
                <mesh filename="package://orient_description/kf2404/meshes/R2000.stl" scale="0.001 0.001 0.001" />
        </geometry>
    </visual>
    
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="scanner_joint" type="fixed">
    <parent link="base_link"/>
    <child link="scanner_link"/>
    <origin xyz="1.0 0 ${lidar_z}" rpy="0 0 0"/>
  </joint>

  <!-- 前轮转向连接件 -->
  <!-- 前轮转向连接件 -->
  <link name="front_wheel_steering">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="5.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>
  <!-- 前轮转向关节 -->
  <joint name="front_wheel_steer_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_wheel_steering"/>
    <origin xyz="${front_wheel_x} 0 ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_wheel">
    <visual>
      <origin rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://turtlebot3_gazebo/models/turtlebot3_common/meshes/wheels/left_tire.stl" scale="0.0065 0.0065 0.0065"/>
        </geometry>
    </visual>
    
    <collision>
      <origin rpy="${pi/2} 0 0"/> 
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.1"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin rpy="${pi/2} 0 0"/> 
      <mass value="${front_wheel_mass}"/>
      <inertia ixx="${front_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"
              ixy="0" ixz="0"
              iyy="${front_wheel_mass*wheel_radius**2/2}"
              iyz="0"
              izz="${front_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"/>
      
    </inertial>
  </link>

  <joint name="front_wheel_joint" type="continuous">
    <parent link="front_wheel_steering"/>
    <child link="front_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>


  <!-- 左后轮 -->
  <link name="left_rear_wheel">
    <visual>
      <origin rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://turtlebot3_gazebo/models/turtlebot3_common/meshes/wheels/left_tire.stl" scale="0.0065 0.0065 0.0065"/>
        </geometry>
    </visual>
    
    <collision>
      <origin rpy="${pi/2} 0 0"/> 
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.1"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin rpy="${pi/2} 0 0"/> 
      <mass value="${back_wheel_mass}"/>
      <inertia ixx="${back_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"
         ixy="0" ixz="0"
         iyy="${back_wheel_mass*wheel_radius**2/2}"
         iyz="0"
         izz="${back_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"/>
    </inertial>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_rear_wheel"/>
    <origin xyz="${rear_wheel_x} ${rear_wheel_y} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- 右后轮 -->
  <link name="right_rear_wheel">
    <visual>
      <origin rpy="0 0 0"/>
      <geometry>
          <mesh filename="package://turtlebot3_gazebo/models/turtlebot3_common/meshes/wheels/right_tire.stl" scale="0.0065 0.0065 0.0065"/>
      </geometry>
    </visual>
    
    <collision>
      <origin rpy="${pi/2} 0 0"/> 
      <geometry>
        <cylinder radius="${wheel_radius}" length="0.1"/>
      </geometry>
    </collision>
 
    <inertial>
      <origin rpy="${pi/2} 0 0"/> 
      <mass value="${back_wheel_mass}"/>
      <inertia ixx="${back_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"
              ixy="0" ixz="0"
              iyy="${back_wheel_mass*wheel_radius**2/2}"
              iyz="0"
              izz="${back_wheel_mass*(3*wheel_radius**2 + 0.01)/12}"/>
    </inertial>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_rear_wheel"/>
    <origin xyz="${rear_wheel_x} ${-rear_wheel_y} ${wheel_z}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>