pf_r2000:
  ros__parameters:
    transport: "udp"
    scanner_ip: "192.168.90.123"
    # port: "3000" # optional
    device: "R2000"
    start_angle: -1800000
    max_num_points_scan: 0
    packet_type: "C"
    scan_topic: "/pf/scan"
    frame_id: "scanner_link"
    watchdogtimeout: 60000
    watchdog: true

orient_laser_scan_filters_node:
  ros__parameters:
    outout_topic: scan/filtered
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.4
        upper_angle: 1.4